repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
        args:
          - --fix=auto
      - id: trailing-whitespace
      - id: flake8

  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
      - id: black
        args: ['--quiet']

  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
      - id: black
        args: ['--quiet']
        name: black-format
        stages: [commit]

  - repo: local
    hooks:
      - id: test_app
        name: test_app 
        stages: [commit]
        types: [python]
        name: pytest-check
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true
